[package]
name = "vigenere-cipher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.7", features = ["derive"] }
indicatif = "0.17.3"
rayon = "1.7.0"
regex = "1"
